<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250207210512 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE archivos_extesionesd (id INT AUTO_INCREMENT NOT NULL, id_tipo_archivos_id INT NOT NULL, id_status_tipo_archivo_id INT NOT NULL, tipo_extesiones VARCHAR(20) NOT NULL, sw_cont_version INT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, INDEX IDX_4118287B8092C4D1 (id_tipo_archivos_id), INDEX IDX_4118287BC7E67E71 (id_status_tipo_archivo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE archivosd (id INT AUTO_INCREMENT NOT NULL, id_tipo_archivo_id INT NOT NULL, id_limited_bloqueo_id INT NOT NULL, idestado_id INT NOT NULL, id_control_archivo_digital_id INT NOT NULL, titulo VARCHAR(255) NOT NULL, tamano INT NOT NULL, nombre_original VARCHAR(50) NOT NULL, url_alojamiento VARCHAR(1000) NOT NULL, publico INT NOT NULL, descripcion_archivo VARCHAR(2000) NOT NULL, nemotecnico VARCHAR(50) NOT NULL, fecha_actividad_registro DATETIME DEFAULT NULL, hashtag VARCHAR(2000) DEFAULT NULL, idempresa_id INT DEFAULT NULL, folios VARCHAR(20) NOT NULL, num_dela_caja VARCHAR(100) DEFAULT NULL, fecha_extrema_inicio DATETIME DEFAULT NULL, fecha_extrema_fin DATETIME DEFAULT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, INDEX IDX_CAAD25FE3E33389B (id_tipo_archivo_id), INDEX IDX_CAAD25FEF5FBF9F2 (id_limited_bloqueo_id), INDEX IDX_CAAD25FEE141EDFE (idestado_id), INDEX IDX_CAAD25FEAC371557 (id_control_archivo_digital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE area (id INT AUTO_INCREMENT NOT NULL, descarea VARCHAR(50) NOT NULL, iddepartamentos INT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categorias_otros (id INT AUTO_INCREMENT NOT NULL, tipcategoria VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contenido_caja (id INT AUTO_INCREMENT NOT NULL, nombre_estuche VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE control_archivo_digital (id INT AUTO_INCREMENT NOT NULL, id_tipo_almacen_id INT DEFAULT NULL, idubica1_id INT DEFAULT NULL, idubica2_id INT DEFAULT NULL, idubica3_id INT DEFAULT NULL, codigo_serie_subserie_id INT NOT NULL, id_status_tipoestado_id INT NOT NULL, idcontenido_caja_id INT DEFAULT NULL, id_estructura_organizativa_id INT NOT NULL, id_pais INT NOT NULL, id_estado INT NOT NULL, id_ciudad INT NOT NULL, asuntos VARCHAR(1000) NOT NULL, fecha_fin_conservac DATETIME DEFAULT NULL, sw_archivo_fisico INT NOT NULL, argumento_justificacion VARCHAR(1000) NOT NULL, num_expediente VARCHAR(50) DEFAULT NULL, fecha_documento DATETIME DEFAULT NULL, cantidad_caja INT NOT NULL, id_user_entrega INT NOT NULL, idempresa_id INT DEFAULT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idregion INT NOT NULL, INDEX IDX_F5FD0BC2E4445FC8 (id_tipo_almacen_id), INDEX IDX_F5FD0BC2556335DE (idubica1_id), INDEX IDX_F5FD0BC247D69A30 (idubica2_id), INDEX IDX_F5FD0BC2FF6AFD55 (idubica3_id), INDEX IDX_F5FD0BC2D894D94 (codigo_serie_subserie_id), INDEX IDX_F5FD0BC24667FB93 (id_status_tipoestado_id), INDEX IDX_F5FD0BC2D6E64AFB (idcontenido_caja_id), INDEX IDX_F5FD0BC2C3AD8E61 (id_estructura_organizativa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE controles_varios (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, normas_internas VARCHAR(2) NOT NULL, inscrito_ivss VARCHAR(2) NOT NULL, forma_ari VARCHAR(2) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE datos_personales (id INT AUTO_INCREMENT NOT NULL, cedula INT NOT NULL, fecha_ingreso DATETIME NOT NULL, familiar_empresa VARCHAR(2) NOT NULL, autorizacion_ingreso VARCHAR(2) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE departamento (id INT AUTO_INCREMENT NOT NULL, descdepartamento VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE direccion_almacen (id INT AUTO_INCREMENT NOT NULL, direccionzona VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, telefono VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documentos_ingresos (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, solicitud_empleo VARCHAR(2) NOT NULL, sintesis_curricular VARCHAR(2) NOT NULL, copia_cedula VARCHAR(2) NOT NULL, constancia_trabajo VARCHAR(2) NOT NULL, reg_informacion_fiscal VARCHAR(2) NOT NULL, verificacion_ref_laborales VARCHAR(2) NOT NULL, certificacion_declaracion_jurada VARCHAR(2) NOT NULL, licencia VARCHAR(2) NOT NULL, certificado_medico VARCHAR(2) NOT NULL, punto_cuenta VARCHAR(2) NOT NULL, poseer_titulo VARCHAR(2) NOT NULL, descripcion_cargo VARCHAR(255) NOT NULL, id_cargo INT DEFAULT NULL, id_departamento INT NOT NULL, id_area INT NOT NULL, id_region INT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, id_confidencialidad VARCHAR(2) NOT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE especialidades_areas (id INT AUTO_INCREMENT NOT NULL, id_personales INT NOT NULL, id_area INT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE estado_conservacion (id INT AUTO_INCREMENT NOT NULL, nombreconservacion VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE estructura_organizativa (id INT AUTO_INCREMENT NOT NULL, padre_id INT DEFAULT NULL, nivel_unidad VARCHAR(100) NOT NULL, estructura_organizativa VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE estudios_academicos (id INT AUTO_INCREMENT NOT NULL, iddatos_personales INT NOT NULL, idprofesion INT NOT NULL, fecha_graduado DATETIME NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fidei_comiso (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, const_depos_prestac_sociales VARCHAR(2) NOT NULL, recibo_anual_intereses VARCHAR(2) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hist_archivo_bloqueadod (id INT AUTO_INCREMENT NOT NULL, idarchivo_id INT NOT NULL, fecha_bloqueo DATETIME NOT NULL, fecha_desbloqueo DATETIME NOT NULL, INDEX IDX_B8C29B938B42E401 (idarchivo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hist_archivo_cont_versiond (id INT AUTO_INCREMENT NOT NULL, id_orientacion_id INT NOT NULL, idarchivo_id INT NOT NULL, id_tipo_operaciones_id INT NOT NULL, iduser INT DEFAULT NULL, tamano INT NOT NULL, url_alojamiento VARCHAR(1000) NOT NULL, ancho INT DEFAULT NULL, altura INT DEFAULT NULL, duracion INT DEFAULT NULL, tags VARCHAR(2000) DEFAULT NULL, fecha_creacion_hist DATETIME DEFAULT NULL, nemotecnico VARCHAR(50) NOT NULL, comentario VARCHAR(500) DEFAULT NULL, nombre_original VARCHAR(50) NOT NULL, idempresa_id INT DEFAULT NULL, INDEX IDX_B1F06F4CA5A2869 (id_orientacion_id), INDEX IDX_B1F06F48B42E401 (idarchivo_id), INDEX IDX_B1F06F47B74D29 (id_tipo_operaciones_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hist_mov_promocion (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, fecha_promocion DATETIME NOT NULL, id_cargo INT DEFAULT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hist_mov_transferencias (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, fecha_transferencia DATETIME NOT NULL, id_departamento INT NOT NULL, id_area INT NOT NULL, id_region INT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hist_movimientos_items (id INT AUTO_INCREMENT NOT NULL, id_user_id INT NOT NULL, id_backlog_padre_id INT DEFAULT NULL, idnivelboardpanel_id INT NOT NULL, idempresa_id INT DEFAULT NULL, titulo VARCHAR(600) NOT NULL, descripcion VARCHAR(2000) DEFAULT NULL, peso INT DEFAULT NULL, INDEX IDX_78923A8F79F37AE5 (id_user_id), INDEX IDX_78923A8F2729068C (id_backlog_padre_id), INDEX IDX_78923A8FB11763F7 (idnivelboardpanel_id), INDEX IDX_78923A8F9FB704AB (idempresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE material_recibido (id INT AUTO_INCREMENT NOT NULL, nombrematerial VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE observacion_eliminacion (id INT AUTO_INCREMENT NOT NULL, id_descripcionerror_id INT NOT NULL, idarchivo_id INT NOT NULL, idusers_elimn INT NOT NULL, observacion VARCHAR(100) DEFAULT NULL, fecha_elimina DATETIME NOT NULL, INDEX IDX_BC06ECB32A6FE4AF (id_descripcionerror_id), INDEX IDX_BC06ECB38B42E401 (idarchivo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE otros (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, expedientes_legal VARCHAR(2) NOT NULL, motivo INT NOT NULL, curso_desarrollo_area_laboral VARCHAR(2) NOT NULL, profesion_orientada_area_servicio VARCHAR(255) NOT NULL, id_categoria_otros INT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE permisos (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, autorizacion_permisos VARCHAR(2) NOT NULL, id_motivo_permiso INT NOT NULL, fecha_desde DATETIME NOT NULL, fecha_hasta DATETIME NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profesion (id INT AUTO_INCREMENT NOT NULL, descprofesion VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prueba (id INT AUTO_INCREMENT NOT NULL, pd LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', prd LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:object)\', dd VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regiond (id INT AUTO_INCREMENT NOT NULL, descregion VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reposo (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, id_tiporeposo INT NOT NULL, id_motivo_reposo INT NOT NULL, fecha_desde DATETIME NOT NULL, fecha_hasta DATETIME NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE roles (id INT AUTO_INCREMENT NOT NULL, roles VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seguridad_salud_laboral (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, ruta_metro VARCHAR(2) NOT NULL, analisis_seguro_trabajo VARCHAR(2) NOT NULL, entrega_equipo_proteccion VARCHAR(2) NOT NULL, constancia_examenes_ocupacionales VARCHAR(2) NOT NULL, constancia_normas_seguridad VARCHAR(2) NOT NULL, copia_registro_delegado VARCHAR(2) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE serie (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sub_serie (id INT AUTO_INCREMENT NOT NULL, id_serie_id INT NOT NULL, nombre_subserie VARCHAR(255) NOT NULL, INDEX IDX_467EF78D89986428 (id_serie_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tamano_archivo_permitidod (id INT AUTO_INCREMENT NOT NULL, id_tipo_archivo_ext_id INT NOT NULL, id_status_tipo_archivo_id INT NOT NULL, tamano INT NOT NULL, sw_cont_version INT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, INDEX IDX_E5DEC856FBF8E41B (id_tipo_archivo_ext_id), INDEX IDX_E5DEC856C7E67E71 (id_status_tipo_archivo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_acccion_registro (id INT AUTO_INCREMENT NOT NULL, idempresa_id INT DEFAULT NULL, accion_registro VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, INDEX IDX_86C472919FB704AB (idempresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_acccion_registrod (id INT AUTO_INCREMENT NOT NULL, accion_registro VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_almacen (id INT AUTO_INCREMENT NOT NULL, iddireccionalmacen_id INT NOT NULL, nombrealmacen VARCHAR(100) NOT NULL, INDEX IDX_C64BF3F09ABB98CF (iddireccionalmacen_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_archivod (id INT AUTO_INCREMENT NOT NULL, nombre_archivo VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa_id INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_descripcion_error (id INT AUTO_INCREMENT NOT NULL, descripcion_error VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_estadod (id INT AUTO_INCREMENT NOT NULL, nombre_status VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa_id INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_input_evaluacion (id INT AUTO_INCREMENT NOT NULL, estatus_id INT DEFAULT NULL, idempresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, seleccion_multiple SMALLINT NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, INDEX IDX_BEC9371F59BAB351 (estatus_id), INDEX IDX_BEC9371F9FB704AB (idempresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_limited_bloqueod (id INT AUTO_INCREMENT NOT NULL, nombre_bloqueo VARCHAR(50) NOT NULL, accion VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa_id INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_motivo_expediente (id INT AUTO_INCREMENT NOT NULL, motivoexpediente VARCHAR(255) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_motivo_permiso (id INT AUTO_INCREMENT NOT NULL, permiso VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_motivo_reposo (id INT AUTO_INCREMENT NOT NULL, motivo VARCHAR(100) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_operacionesd (id INT AUTO_INCREMENT NOT NULL, operacion VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa_id INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_orientaciond (id INT AUTO_INCREMENT NOT NULL, nombre_orientacion VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa_id INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_reposo (id INT AUTO_INCREMENT NOT NULL, tiporeposo VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_status_archivod (id INT AUTO_INCREMENT NOT NULL, nombrestatus VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_vacaciones (id INT AUTO_INCREMENT NOT NULL, vacaciones VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipos_respuestas (id INT AUTO_INCREMENT NOT NULL, respuestas VARCHAR(50) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE token_pdf (id INT AUTO_INCREMENT NOT NULL, id_user INT NOT NULL, datos_qr VARCHAR(255) NOT NULL, create_at DATETIME NOT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ubicacion (id INT AUTO_INCREMENT NOT NULL, descripcion VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_archivo_bloqueadod (id INT AUTO_INCREMENT NOT NULL, idarchivo_id INT NOT NULL, fecha_bloqueo DATETIME NOT NULL, INDEX IDX_8A813B9D8B42E401 (idarchivo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_archivosd (id INT AUTO_INCREMENT NOT NULL, iduserarchivos_id INT NOT NULL, idusuario_id INT DEFAULT NULL, idempresa_id INT DEFAULT NULL, INDEX IDX_4396CFEC730F69E5 (iduserarchivos_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vacaciones_observacion (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, observacion VARCHAR(2000) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vaciones (id INT AUTO_INCREMENT NOT NULL, id_datos_personales INT NOT NULL, autorizacion_vacaciones VARCHAR(2) NOT NULL, periodos_acumulados INT DEFAULT NULL, id_tipo_vacaciones INT NOT NULL, fecha_desde DATETIME NOT NULL, fecha_hasta DATETIME NOT NULL, fecha_incorporacion DATETIME NOT NULL, periodo_difrute VARCHAR(20) NOT NULL, create_at DATETIME DEFAULT NULL, create_by VARCHAR(255) DEFAULT NULL, update_at DATETIME DEFAULT NULL, update_by VARCHAR(255) DEFAULT NULL, idempresa INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE archivos_extesionesd ADD CONSTRAINT FK_4118287B8092C4D1 FOREIGN KEY (id_tipo_archivos_id) REFERENCES tipo_archivod (id)');
        $this->addSql('ALTER TABLE archivos_extesionesd ADD CONSTRAINT FK_4118287BC7E67E71 FOREIGN KEY (id_status_tipo_archivo_id) REFERENCES tipo_status_archivod (id)');
        $this->addSql('ALTER TABLE archivosd ADD CONSTRAINT FK_CAAD25FE3E33389B FOREIGN KEY (id_tipo_archivo_id) REFERENCES tipo_archivod (id)');
        $this->addSql('ALTER TABLE archivosd ADD CONSTRAINT FK_CAAD25FEF5FBF9F2 FOREIGN KEY (id_limited_bloqueo_id) REFERENCES tipo_limited_bloqueod (id)');
        $this->addSql('ALTER TABLE archivosd ADD CONSTRAINT FK_CAAD25FEE141EDFE FOREIGN KEY (idestado_id) REFERENCES tipo_estadod (id)');
        $this->addSql('ALTER TABLE archivosd ADD CONSTRAINT FK_CAAD25FEAC371557 FOREIGN KEY (id_control_archivo_digital_id) REFERENCES control_archivo_digital (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC2E4445FC8 FOREIGN KEY (id_tipo_almacen_id) REFERENCES tipo_almacen (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC2556335DE FOREIGN KEY (idubica1_id) REFERENCES ubicacion (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC247D69A30 FOREIGN KEY (idubica2_id) REFERENCES ubicacion (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC2FF6AFD55 FOREIGN KEY (idubica3_id) REFERENCES ubicacion (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC2D894D94 FOREIGN KEY (codigo_serie_subserie_id) REFERENCES sub_serie (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC24667FB93 FOREIGN KEY (id_status_tipoestado_id) REFERENCES tipo_status_archivod (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC2D6E64AFB FOREIGN KEY (idcontenido_caja_id) REFERENCES contenido_caja (id)');
        $this->addSql('ALTER TABLE control_archivo_digital ADD CONSTRAINT FK_F5FD0BC2C3AD8E61 FOREIGN KEY (id_estructura_organizativa_id) REFERENCES estructura_organizativa (id)');
        $this->addSql('ALTER TABLE hist_archivo_bloqueadod ADD CONSTRAINT FK_B8C29B938B42E401 FOREIGN KEY (idarchivo_id) REFERENCES archivosd (id)');
        $this->addSql('ALTER TABLE hist_archivo_cont_versiond ADD CONSTRAINT FK_B1F06F4CA5A2869 FOREIGN KEY (id_orientacion_id) REFERENCES tipo_orientaciond (id)');
        $this->addSql('ALTER TABLE hist_archivo_cont_versiond ADD CONSTRAINT FK_B1F06F48B42E401 FOREIGN KEY (idarchivo_id) REFERENCES archivosd (id)');
        $this->addSql('ALTER TABLE hist_archivo_cont_versiond ADD CONSTRAINT FK_B1F06F47B74D29 FOREIGN KEY (id_tipo_operaciones_id) REFERENCES tipo_operacionesd (id)');
        $this->addSql('ALTER TABLE hist_movimientos_items ADD CONSTRAINT FK_78923A8F79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE hist_movimientos_items ADD CONSTRAINT FK_78923A8F2729068C FOREIGN KEY (id_backlog_padre_id) REFERENCES items (id)');
        $this->addSql('ALTER TABLE hist_movimientos_items ADD CONSTRAINT FK_78923A8FB11763F7 FOREIGN KEY (idnivelboardpanel_id) REFERENCES nivel_board_panel (id)');
        $this->addSql('ALTER TABLE hist_movimientos_items ADD CONSTRAINT FK_78923A8F9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE observacion_eliminacion ADD CONSTRAINT FK_BC06ECB32A6FE4AF FOREIGN KEY (id_descripcionerror_id) REFERENCES tipo_descripcion_error (id)');
        $this->addSql('ALTER TABLE observacion_eliminacion ADD CONSTRAINT FK_BC06ECB38B42E401 FOREIGN KEY (idarchivo_id) REFERENCES archivosd (id)');
        $this->addSql('ALTER TABLE sub_serie ADD CONSTRAINT FK_467EF78D89986428 FOREIGN KEY (id_serie_id) REFERENCES serie (id)');
        $this->addSql('ALTER TABLE tamano_archivo_permitidod ADD CONSTRAINT FK_E5DEC856FBF8E41B FOREIGN KEY (id_tipo_archivo_ext_id) REFERENCES archivos_extesionesd (id)');
        $this->addSql('ALTER TABLE tamano_archivo_permitidod ADD CONSTRAINT FK_E5DEC856C7E67E71 FOREIGN KEY (id_status_tipo_archivo_id) REFERENCES tipo_archivod (id)');
        $this->addSql('ALTER TABLE tipo_acccion_registro ADD CONSTRAINT FK_86C472919FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_almacen ADD CONSTRAINT FK_C64BF3F09ABB98CF FOREIGN KEY (iddireccionalmacen_id) REFERENCES direccion_almacen (id)');
        $this->addSql('ALTER TABLE tipo_input_evaluacion ADD CONSTRAINT FK_BEC9371F59BAB351 FOREIGN KEY (estatus_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tipo_input_evaluacion ADD CONSTRAINT FK_BEC9371F9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueadod ADD CONSTRAINT FK_8A813B9D8B42E401 FOREIGN KEY (idarchivo_id) REFERENCES archivosd (id)');
        $this->addSql('ALTER TABLE usuario_archivosd ADD CONSTRAINT FK_4396CFEC730F69E5 FOREIGN KEY (iduserarchivos_id) REFERENCES archivosd (id)');
        $this->addSql('DROP TABLE actualiza_nacimiento');
        $this->addSql('DROP TABLE reporte');
        $this->addSql('DROP TABLE reporte_rol');
        $this->addSql('ALTER TABLE archivos CHANGE nombre_original nombre_original VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE archivos_extesiones ADD CONSTRAINT FK_13386BE9C7E67E71 FOREIGN KEY (id_status_tipo_archivo_id) REFERENCES tipo_status_archivo (id)');
        $this->addSql('ALTER TABLE calendar_event_correo_notif DROP fecha_entrega');
        $this->addSql('ALTER TABLE calendar_event_correo_notif ADD CONSTRAINT FK_B88432AD9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('CREATE INDEX IDX_B88432AD9FB704AB ON calendar_event_correo_notif (idempresa_id)');
        $this->addSql('DROP INDEX IDX_E355AA122A676DE7 ON coordinacion');
        $this->addSql('ALTER TABLE empresa CHANGE url_logo url_logo VARCHAR(1000) NOT NULL');
        $this->addSql('ALTER TABLE estado DROP idregion_id, CHANGE pais_id pais_id INT DEFAULT NULL, CHANGE nombre nombre VARCHAR(255) DEFAULT NULL, CHANGE idempresa_id idempresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE estado ADD CONSTRAINT FK_265DE1E36BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE estado ADD CONSTRAINT FK_265DE1E3C604D5C6 FOREIGN KEY (pais_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE estado ADD CONSTRAINT FK_265DE1E39FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('CREATE INDEX IDX_265DE1E36BF700BD ON estado (status_id)');
        $this->addSql('CREATE INDEX IDX_265DE1E3C604D5C6 ON estado (pais_id)');
        $this->addSql('CREATE INDEX IDX_265DE1E39FB704AB ON estado (idempresa_id)');
        $this->addSql('ALTER TABLE evaluacion DROP FOREIGN KEY FK_DEEDCA5342094404');
        $this->addSql('ALTER TABLE evaluacion ADD CONSTRAINT FK_DEEDCA5342094404 FOREIGN KEY (id_tipo_unidad_id) REFERENCES tipo_unidad (id)');
        $this->addSql('DROP INDEX IDX_6E583517881ECFA7 ON gerencia');
        $this->addSql('ALTER TABLE hist_archivo_bloqueado CHANGE fecha_bloqueo fecha_bloqueo DATETIME NOT NULL, CHANGE fecha_desbloqueo fecha_desbloqueo DATETIME NOT NULL');
        $this->addSql('ALTER TABLE hist_archivo_cont_version CHANGE nombre_original nombre_original VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE instrumento_eva_acreditacion ADD CONSTRAINT FK_1551CB1C9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('CREATE INDEX IDX_1551CB1C9FB704AB ON instrumento_eva_acreditacion (idempresa_id)');
        $this->addSql('ALTER TABLE instrumento_usuario DROP FOREIGN KEY FK_440D088793FF8F9C');
        $this->addSql('ALTER TABLE instrumento_usuario DROP FOREIGN KEY FK_440D0887A76ED395');
        $this->addSql('DROP INDEX IDX_440D088793FF8F9C ON instrumento_usuario');
        $this->addSql('DROP INDEX IDX_440D0887A76ED395 ON instrumento_usuario');
        $this->addSql('ALTER TABLE instrumento_usuario ADD CONSTRAINT FK_D9B531F3396DC676 FOREIGN KEY (id_instrumento_id) REFERENCES instrumento_captura (id)');
        $this->addSql('ALTER TABLE instrumento_usuario ADD CONSTRAINT FK_D9B531F379F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE instrumento_usuario ADD CONSTRAINT FK_D9B531F3841DA47 FOREIGN KEY (pais_id_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE instrumento_usuario ADD CONSTRAINT FK_D9B531F375BF18A5 FOREIGN KEY (estado_id_id) REFERENCES estado (id)');
        $this->addSql('ALTER TABLE instrumento_usuario ADD CONSTRAINT FK_D9B531F39FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE item_acreditacion ADD CONSTRAINT FK_72925F962257068C FOREIGN KEY (id_tipo_item_id) REFERENCES tipo_item (id)');
        $this->addSql('ALTER TABLE item_acreditacion ADD CONSTRAINT FK_72925F969FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE item_adjunto ADD CONSTRAINT FK_73E1EA64CCF2FB2E FOREIGN KEY (id_item_id) REFERENCES items (id)');
        $this->addSql('ALTER TABLE item_adjunto ADD CONSTRAINT FK_73E1EA6479F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE item_adjunto ADD CONSTRAINT FK_73E1EA649FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE item_comentario ADD CONSTRAINT FK_F620CF08126F525E FOREIGN KEY (item_id) REFERENCES items (id)');
        $this->addSql('ALTER TABLE item_comentario ADD CONSTRAINT FK_F620CF0879F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE item_comentario ADD CONSTRAINT FK_F620CF089FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE items CHANGE id_user_id id_user_id INT NOT NULL');
        $this->addSql('ALTER TABLE items ADD CONSTRAINT FK_E11EE94D79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE items ADD CONSTRAINT FK_E11EE94D2729068C FOREIGN KEY (id_backlog_padre_id) REFERENCES items (id)');
        $this->addSql('ALTER TABLE items ADD CONSTRAINT FK_E11EE94DB11763F7 FOREIGN KEY (idnivelboardpanel_id) REFERENCES nivel_board_panel (id)');
        $this->addSql('ALTER TABLE items ADD CONSTRAINT FK_E11EE94D32F43F80 FOREIGN KEY (idstatusisuues_id) REFERENCES statusisuues (id)');
        $this->addSql('ALTER TABLE items ADD CONSTRAINT FK_E11EE94DE5F1371 FOREIGN KEY (id_typeevent_id) REFERENCES type_event (id)');
        $this->addSql('ALTER TABLE items ADD CONSTRAINT FK_E11EE94D9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE modulo ADD CONSTRAINT FK_ECF1CF366BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE modulo ADD CONSTRAINT FK_ECF1CF36613CEC58 FOREIGN KEY (padre_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE modulo ADD CONSTRAINT FK_ECF1CF369FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('DROP INDEX FK_A8962E626BF700BD ON modulo_rol');
        $this->addSql('ALTER TABLE modulo_rol ADD CONSTRAINT FK_A8962E624BAB96C FOREIGN KEY (rol_id) REFERENCES rol (id)');
        $this->addSql('ALTER TABLE modulo_rol ADD CONSTRAINT FK_A8962E62C07F55F5 FOREIGN KEY (modulo_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE modulo_rol ADD CONSTRAINT FK_A8962E626BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE modulo_rol ADD CONSTRAINT FK_A8962E629FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE nivel ADD CONSTRAINT FK_AAFC20CB6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE nivel ADD CONSTRAINT FK_AAFC20CB9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE opciones CHANGE puntos puntos DOUBLE PRECISION NOT NULL');
        $this->addSql('ALTER TABLE opciones_cargo ADD CONSTRAINT FK_348153355BDBF2F FOREIGN KEY (opcion_id) REFERENCES opciones (id)');
        $this->addSql('ALTER TABLE opciones_cargo ADD CONSTRAINT FK_34815335D1E12F15 FOREIGN KEY (id_cargo_id) REFERENCES cargo (id)');
        $this->addSql('ALTER TABLE opciones_cargo ADD CONSTRAINT FK_348153359FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE pais ADD CONSTRAINT FK_7E5D2EFF6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE pais ADD CONSTRAINT FK_7E5D2EFF9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE parametros ADD CONSTRAINT FK_E09691179FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE pregunta ADD CONSTRAINT FK_AEE0E1F76699F643 FOREIGN KEY (id_input_id) REFERENCES tipo_input (id)');
        $this->addSql('ALTER TABLE pregunta ADD CONSTRAINT FK_AEE0E1F710560508 FOREIGN KEY (id_categoria_id) REFERENCES tipo_categoria (id)');
        $this->addSql('ALTER TABLE pregunta ADD CONSTRAINT FK_AEE0E1F7396DC676 FOREIGN KEY (id_instrumento_id) REFERENCES instrumento_captura (id)');
        $this->addSql('ALTER TABLE pregunta ADD CONSTRAINT FK_AEE0E1F77A5A413A FOREIGN KEY (seccion_id) REFERENCES seccion (id)');
        $this->addSql('ALTER TABLE pregunta ADD CONSTRAINT FK_AEE0E1F79FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE pregunta_evaluacion ADD CONSTRAINT FK_408F5ADE6699F643 FOREIGN KEY (id_input_id) REFERENCES tipo_input (id)');
        $this->addSql('ALTER TABLE pregunta_evaluacion ADD CONSTRAINT FK_408F5ADE10560508 FOREIGN KEY (id_categoria_id) REFERENCES tipo_categoria_evaluacion (id)');
        $this->addSql('ALTER TABLE pregunta_evaluacion ADD CONSTRAINT FK_408F5ADE593D2563 FOREIGN KEY (id_evaluacion_id) REFERENCES evaluacion (id)');
        $this->addSql('ALTER TABLE pregunta_evaluacion ADD CONSTRAINT FK_408F5ADE7A5A413A FOREIGN KEY (seccion_id) REFERENCES seccion_evaluacion (id)');
        $this->addSql('ALTER TABLE pregunta_evaluacion ADD CONSTRAINT FK_408F5ADE9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE proyecto ADD CONSTRAINT FK_6FD202B99FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE proyecto ADD CONSTRAINT FK_6FD202B95C473223 FOREIGN KEY (id_user_pmo_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE proyecto ADD CONSTRAINT FK_6FD202B9973E620A FOREIGN KEY (idstatuscalendarioproyecto_id) REFERENCES statuscalendarioproyecto (id)');
        $this->addSql('ALTER TABLE proyecto_rol ADD CONSTRAINT FK_4EC328E7F625D1BA FOREIGN KEY (proyecto_id) REFERENCES proyecto (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE proyecto_rol ADD CONSTRAINT FK_4EC328E74BAB96C FOREIGN KEY (rol_id) REFERENCES rol (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE proyecto_adjunto ADD CONSTRAINT FK_1646AC50EE371C4D FOREIGN KEY (id_proyecto_id) REFERENCES proyecto (id)');
        $this->addSql('ALTER TABLE proyecto_adjunto ADD CONSTRAINT FK_1646AC5079F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE proyecto_adjunto ADD CONSTRAINT FK_1646AC509FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE recurso ADD CONSTRAINT FK_B2BB37647DAF9E19 FOREIGN KEY (proyecto_id_id) REFERENCES proyecto (id)');
        $this->addSql('ALTER TABLE recurso ADD CONSTRAINT FK_B2BB376467B3B43D FOREIGN KEY (users_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE recurso ADD CONSTRAINT FK_B2BB37649FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE recursos_proyecto ADD CONSTRAINT FK_F7C598F330E4A115 FOREIGN KEY (idproyecto_id) REFERENCES proyecto (id)');
        $this->addSql('ALTER TABLE recursos_proyecto ADD CONSTRAINT FK_F7C598F328827174 FOREIGN KEY (idrecurso_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE recursos_proyecto ADD CONSTRAINT FK_F7C598F39FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE redes ADD CONSTRAINT FK_D7909F1B8700013 FOREIGN KEY (tiporedes_id_id) REFERENCES tiporedes (id)');
        $this->addSql('ALTER TABLE redes ADD CONSTRAINT FK_D7909F1B380CE5D8 FOREIGN KEY (id_user_id_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE redes ADD CONSTRAINT FK_D7909F1B9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE respuesta ADD CONSTRAINT FK_6C6EC5EE79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE respuesta ADD CONSTRAINT FK_6C6EC5EE29B74DE9 FOREIGN KEY (id_pregunta_id) REFERENCES pregunta (id)');
        $this->addSql('ALTER TABLE respuesta ADD CONSTRAINT FK_6C6EC5EE85880308 FOREIGN KEY (id_opcion_id) REFERENCES opciones (id)');
        $this->addSql('ALTER TABLE respuesta ADD CONSTRAINT FK_6C6EC5EE9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE respuesta_evaluacion ADD CONSTRAINT FK_459698AD79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE respuesta_evaluacion ADD CONSTRAINT FK_459698AD29B74DE9 FOREIGN KEY (id_pregunta_id) REFERENCES pregunta_evaluacion (id)');
        $this->addSql('ALTER TABLE respuesta_evaluacion ADD CONSTRAINT FK_459698AD85880308 FOREIGN KEY (id_opcion_id) REFERENCES opciones_evaluacion (id)');
        $this->addSql('ALTER TABLE respuesta_evaluacion ADD CONSTRAINT FK_459698AD9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE rol ADD CONSTRAINT FK_E553F37EBC2BC9A FOREIGN KEY (id_status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE rol ADD CONSTRAINT FK_E553F379FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE seccion ADD CONSTRAINT FK_E0BD15C940B7B70 FOREIGN KEY (instrumento_id) REFERENCES instrumento_captura (id)');
        $this->addSql('ALTER TABLE seccion ADD CONSTRAINT FK_E0BD15C96BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE seccion ADD CONSTRAINT FK_E0BD15C99FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE seccion_evaluacion ADD CONSTRAINT FK_9C3E60D9E715F406 FOREIGN KEY (evaluacion_id) REFERENCES evaluacion (id)');
        $this->addSql('ALTER TABLE seccion_evaluacion ADD CONSTRAINT FK_9C3E60D96BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE seccion_evaluacion ADD CONSTRAINT FK_9C3E60D99FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE spring DROP total_remaning_max');
        $this->addSql('ALTER TABLE spring ADD CONSTRAINT FK_6B3E146930E4A115 FOREIGN KEY (idproyecto_id) REFERENCES proyecto (id)');
        $this->addSql('ALTER TABLE spring ADD CONSTRAINT FK_6B3E14699FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE sprint_item ADD CONSTRAINT FK_24D98A324EBD432D FOREIGN KEY (id_spring_id) REFERENCES spring (id)');
        $this->addSql('ALTER TABLE sprint_item ADD CONSTRAINT FK_24D98A32CCF2FB2E FOREIGN KEY (id_item_id) REFERENCES items (id)');
        $this->addSql('ALTER TABLE sprint_item ADD CONSTRAINT FK_24D98A329FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE status ADD CONSTRAINT FK_7B00651C9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE statuscalendarioproyecto ADD CONSTRAINT FK_241B1CFC9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE statusisuues ADD CONSTRAINT FK_82749D339FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE statuslaboral ADD CONSTRAINT FK_B98B620D9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tamano_archivo_permitido ADD CONSTRAINT FK_41C2B8FFBF8E41B FOREIGN KEY (id_tipo_archivo_ext_id) REFERENCES archivos_extesiones (id)');
        $this->addSql('ALTER TABLE tamano_archivo_permitido ADD CONSTRAINT FK_41C2B8FC7E67E71 FOREIGN KEY (id_status_tipo_archivo_id) REFERENCES tipo_archivo (id)');
        $this->addSql('ALTER TABLE tamano_archivo_permitido ADD CONSTRAINT FK_41C2B8F9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE telefono ADD CONSTRAINT FK_C1E70A7F79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE telefono ADD CONSTRAINT FK_C1E70A7FEBC2BC9A FOREIGN KEY (id_status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE telefono ADD CONSTRAINT FK_C1E70A7F9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_archivo ADD CONSTRAINT FK_26D095229FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_categoria ADD CONSTRAINT FK_AC7EAD636BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tipo_categoria ADD CONSTRAINT FK_AC7EAD639FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_categoria_evaluacion ADD CONSTRAINT FK_EDB5A1F76BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tipo_categoria_evaluacion ADD CONSTRAINT FK_EDB5A1F79FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_cuenta_email ADD CONSTRAINT FK_62E3A4549FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_estado ADD CONSTRAINT FK_B3E417FB9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_input ADD CONSTRAINT FK_DE94A81F59BAB351 FOREIGN KEY (estatus_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tipo_input ADD CONSTRAINT FK_DE94A81F9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_item CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE tipo_item ADD CONSTRAINT FK_1534F25B9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_limited_bloqueo ADD CONSTRAINT FK_101220889FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_operaciones ADD CONSTRAINT FK_544EBBF69FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_orientacion ADD CONSTRAINT FK_CE6A84889FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_status_archivo ADD CONSTRAINT FK_B12A0CA79FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_unidad ADD CONSTRAINT FK_665F26376BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tipo_unidad ADD CONSTRAINT FK_665F26379FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tipo_unidad_evaluacion ADD CONSTRAINT FK_45DB30B86BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tipo_unidad_evaluacion ADD CONSTRAINT FK_45DB30B89FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE tiporedes ADD CONSTRAINT FK_809A38456BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tiporedes ADD CONSTRAINT FK_809A38459FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE token ADD CONSTRAINT FK_5F37A13B79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE token ADD CONSTRAINT FK_5F37A13B9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE type_event ADD CONSTRAINT FK_35A28D509FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('DROP INDEX FK_8D93D649D682C705 ON user');
        $this->addSql('DROP INDEX FK_8D93D649CE9EB679 ON user');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueado ADD CONSTRAINT FK_EB980159786A81FB FOREIGN KEY (iduser_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueado ADD CONSTRAINT FK_EB9801598B42E401 FOREIGN KEY (idarchivo_id) REFERENCES archivos (id)');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueado ADD CONSTRAINT FK_EB9801599FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE usuario_archivos ADD CONSTRAINT FK_F04CF62A16915EA4 FOREIGN KEY (idusuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE usuario_archivos ADD CONSTRAINT FK_F04CF62A730F69E5 FOREIGN KEY (iduserarchivos_id) REFERENCES archivos (id)');
        $this->addSql('ALTER TABLE usuario_archivos ADD CONSTRAINT FK_F04CF62A9FB704AB FOREIGN KEY (idempresa_id) REFERENCES empresa (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tamano_archivo_permitidod DROP FOREIGN KEY FK_E5DEC856FBF8E41B');
        $this->addSql('ALTER TABLE hist_archivo_bloqueadod DROP FOREIGN KEY FK_B8C29B938B42E401');
        $this->addSql('ALTER TABLE hist_archivo_cont_versiond DROP FOREIGN KEY FK_B1F06F48B42E401');
        $this->addSql('ALTER TABLE observacion_eliminacion DROP FOREIGN KEY FK_BC06ECB38B42E401');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueadod DROP FOREIGN KEY FK_8A813B9D8B42E401');
        $this->addSql('ALTER TABLE usuario_archivosd DROP FOREIGN KEY FK_4396CFEC730F69E5');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC2D6E64AFB');
        $this->addSql('ALTER TABLE archivosd DROP FOREIGN KEY FK_CAAD25FEAC371557');
        $this->addSql('ALTER TABLE tipo_almacen DROP FOREIGN KEY FK_C64BF3F09ABB98CF');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC2C3AD8E61');
        $this->addSql('ALTER TABLE sub_serie DROP FOREIGN KEY FK_467EF78D89986428');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC2D894D94');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC2E4445FC8');
        $this->addSql('ALTER TABLE archivos_extesionesd DROP FOREIGN KEY FK_4118287B8092C4D1');
        $this->addSql('ALTER TABLE archivosd DROP FOREIGN KEY FK_CAAD25FE3E33389B');
        $this->addSql('ALTER TABLE tamano_archivo_permitidod DROP FOREIGN KEY FK_E5DEC856C7E67E71');
        $this->addSql('ALTER TABLE observacion_eliminacion DROP FOREIGN KEY FK_BC06ECB32A6FE4AF');
        $this->addSql('ALTER TABLE archivosd DROP FOREIGN KEY FK_CAAD25FEE141EDFE');
        $this->addSql('ALTER TABLE archivosd DROP FOREIGN KEY FK_CAAD25FEF5FBF9F2');
        $this->addSql('ALTER TABLE hist_archivo_cont_versiond DROP FOREIGN KEY FK_B1F06F47B74D29');
        $this->addSql('ALTER TABLE hist_archivo_cont_versiond DROP FOREIGN KEY FK_B1F06F4CA5A2869');
        $this->addSql('ALTER TABLE archivos_extesionesd DROP FOREIGN KEY FK_4118287BC7E67E71');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC24667FB93');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC2556335DE');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC247D69A30');
        $this->addSql('ALTER TABLE control_archivo_digital DROP FOREIGN KEY FK_F5FD0BC2FF6AFD55');
        $this->addSql('CREATE TABLE actualiza_nacimiento (cedula VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, fecha VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, sw INT DEFAULT NULL) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reporte (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, iddashboard VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, descripcion VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reporte_rol (id INT AUTO_INCREMENT NOT NULL, idrol_id INT NOT NULL, idreporte_id INT NOT NULL, INDEX IDX_DB836B11600714C0 (idrol_id), INDEX IDX_DB836B11C485B848 (idreporte_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE archivos_extesionesd');
        $this->addSql('DROP TABLE archivosd');
        $this->addSql('DROP TABLE area');
        $this->addSql('DROP TABLE categorias_otros');
        $this->addSql('DROP TABLE contenido_caja');
        $this->addSql('DROP TABLE control_archivo_digital');
        $this->addSql('DROP TABLE controles_varios');
        $this->addSql('DROP TABLE datos_personales');
        $this->addSql('DROP TABLE departamento');
        $this->addSql('DROP TABLE direccion_almacen');
        $this->addSql('DROP TABLE documentos_ingresos');
        $this->addSql('DROP TABLE especialidades_areas');
        $this->addSql('DROP TABLE estado_conservacion');
        $this->addSql('DROP TABLE estructura_organizativa');
        $this->addSql('DROP TABLE estudios_academicos');
        $this->addSql('DROP TABLE fidei_comiso');
        $this->addSql('DROP TABLE hist_archivo_bloqueadod');
        $this->addSql('DROP TABLE hist_archivo_cont_versiond');
        $this->addSql('DROP TABLE hist_mov_promocion');
        $this->addSql('DROP TABLE hist_mov_transferencias');
        $this->addSql('DROP TABLE hist_movimientos_items');
        $this->addSql('DROP TABLE material_recibido');
        $this->addSql('DROP TABLE observacion_eliminacion');
        $this->addSql('DROP TABLE otros');
        $this->addSql('DROP TABLE permisos');
        $this->addSql('DROP TABLE profesion');
        $this->addSql('DROP TABLE prueba');
        $this->addSql('DROP TABLE regiond');
        $this->addSql('DROP TABLE reposo');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE seguridad_salud_laboral');
        $this->addSql('DROP TABLE serie');
        $this->addSql('DROP TABLE sub_serie');
        $this->addSql('DROP TABLE tamano_archivo_permitidod');
        $this->addSql('DROP TABLE tipo_acccion_registro');
        $this->addSql('DROP TABLE tipo_acccion_registrod');
        $this->addSql('DROP TABLE tipo_almacen');
        $this->addSql('DROP TABLE tipo_archivod');
        $this->addSql('DROP TABLE tipo_descripcion_error');
        $this->addSql('DROP TABLE tipo_estadod');
        $this->addSql('DROP TABLE tipo_input_evaluacion');
        $this->addSql('DROP TABLE tipo_limited_bloqueod');
        $this->addSql('DROP TABLE tipo_motivo_expediente');
        $this->addSql('DROP TABLE tipo_motivo_permiso');
        $this->addSql('DROP TABLE tipo_motivo_reposo');
        $this->addSql('DROP TABLE tipo_operacionesd');
        $this->addSql('DROP TABLE tipo_orientaciond');
        $this->addSql('DROP TABLE tipo_reposo');
        $this->addSql('DROP TABLE tipo_status_archivod');
        $this->addSql('DROP TABLE tipo_vacaciones');
        $this->addSql('DROP TABLE tipos_respuestas');
        $this->addSql('DROP TABLE token_pdf');
        $this->addSql('DROP TABLE ubicacion');
        $this->addSql('DROP TABLE usuario_archivo_bloqueadod');
        $this->addSql('DROP TABLE usuario_archivosd');
        $this->addSql('DROP TABLE vacaciones_observacion');
        $this->addSql('DROP TABLE vaciones');
        $this->addSql('ALTER TABLE archivos CHANGE nombre_original nombre_original VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE archivos_extesiones DROP FOREIGN KEY FK_13386BE9C7E67E71');
        $this->addSql('ALTER TABLE calendar_event_correo_notif DROP FOREIGN KEY FK_B88432AD9FB704AB');
        $this->addSql('DROP INDEX IDX_B88432AD9FB704AB ON calendar_event_correo_notif');
        $this->addSql('ALTER TABLE calendar_event_correo_notif ADD fecha_entrega DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_E355AA122A676DE7 ON coordinacion (id_status_id)');
        $this->addSql('ALTER TABLE empresa CHANGE url_logo url_logo VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE estado DROP FOREIGN KEY FK_265DE1E36BF700BD');
        $this->addSql('ALTER TABLE estado DROP FOREIGN KEY FK_265DE1E3C604D5C6');
        $this->addSql('ALTER TABLE estado DROP FOREIGN KEY FK_265DE1E39FB704AB');
        $this->addSql('DROP INDEX IDX_265DE1E36BF700BD ON estado');
        $this->addSql('DROP INDEX IDX_265DE1E3C604D5C6 ON estado');
        $this->addSql('DROP INDEX IDX_265DE1E39FB704AB ON estado');
        $this->addSql('ALTER TABLE estado ADD idregion_id INT NOT NULL, CHANGE pais_id pais_id INT NOT NULL, CHANGE idempresa_id idempresa_id INT NOT NULL, CHANGE nombre nombre VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`');
        $this->addSql('ALTER TABLE evaluacion DROP FOREIGN KEY FK_DEEDCA5342094404');
        $this->addSql('ALTER TABLE evaluacion ADD CONSTRAINT FK_DEEDCA5342094404 FOREIGN KEY (id_tipo_unidad_id) REFERENCES tipo_unidad_evaluacion (id)');
        $this->addSql('CREATE INDEX IDX_6E583517881ECFA7 ON gerencia (id_status_id)');
        $this->addSql('ALTER TABLE hist_archivo_bloqueado CHANGE fecha_bloqueo fecha_bloqueo DATETIME DEFAULT NULL, CHANGE fecha_desbloqueo fecha_desbloqueo DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE hist_archivo_cont_version CHANGE nombre_original nombre_original VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE instrumento_eva_acreditacion DROP FOREIGN KEY FK_1551CB1C9FB704AB');
        $this->addSql('DROP INDEX IDX_1551CB1C9FB704AB ON instrumento_eva_acreditacion');
        $this->addSql('ALTER TABLE instrumento_usuario DROP FOREIGN KEY FK_D9B531F3396DC676');
        $this->addSql('ALTER TABLE instrumento_usuario DROP FOREIGN KEY FK_D9B531F379F37AE5');
        $this->addSql('ALTER TABLE instrumento_usuario DROP FOREIGN KEY FK_D9B531F3841DA47');
        $this->addSql('ALTER TABLE instrumento_usuario DROP FOREIGN KEY FK_D9B531F375BF18A5');
        $this->addSql('ALTER TABLE instrumento_usuario DROP FOREIGN KEY FK_D9B531F39FB704AB');
        $this->addSql('ALTER TABLE instrumento_usuario ADD CONSTRAINT FK_440D088793FF8F9C FOREIGN KEY (id_instrumento_id) REFERENCES instrumento_captura (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE instrumento_usuario ADD CONSTRAINT FK_440D0887A76ED395 FOREIGN KEY (id_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_440D088793FF8F9C ON instrumento_usuario (id_instrumento_id)');
        $this->addSql('CREATE INDEX IDX_440D0887A76ED395 ON instrumento_usuario (id_user_id)');
        $this->addSql('ALTER TABLE item_acreditacion DROP FOREIGN KEY FK_72925F962257068C');
        $this->addSql('ALTER TABLE item_acreditacion DROP FOREIGN KEY FK_72925F969FB704AB');
        $this->addSql('ALTER TABLE item_adjunto DROP FOREIGN KEY FK_73E1EA64CCF2FB2E');
        $this->addSql('ALTER TABLE item_adjunto DROP FOREIGN KEY FK_73E1EA6479F37AE5');
        $this->addSql('ALTER TABLE item_adjunto DROP FOREIGN KEY FK_73E1EA649FB704AB');
        $this->addSql('ALTER TABLE item_comentario DROP FOREIGN KEY FK_F620CF08126F525E');
        $this->addSql('ALTER TABLE item_comentario DROP FOREIGN KEY FK_F620CF0879F37AE5');
        $this->addSql('ALTER TABLE item_comentario DROP FOREIGN KEY FK_F620CF089FB704AB');
        $this->addSql('ALTER TABLE items DROP FOREIGN KEY FK_E11EE94D79F37AE5');
        $this->addSql('ALTER TABLE items DROP FOREIGN KEY FK_E11EE94D2729068C');
        $this->addSql('ALTER TABLE items DROP FOREIGN KEY FK_E11EE94DB11763F7');
        $this->addSql('ALTER TABLE items DROP FOREIGN KEY FK_E11EE94D32F43F80');
        $this->addSql('ALTER TABLE items DROP FOREIGN KEY FK_E11EE94DE5F1371');
        $this->addSql('ALTER TABLE items DROP FOREIGN KEY FK_E11EE94D9FB704AB');
        $this->addSql('ALTER TABLE items CHANGE id_user_id id_user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE modulo DROP FOREIGN KEY FK_ECF1CF366BF700BD');
        $this->addSql('ALTER TABLE modulo DROP FOREIGN KEY FK_ECF1CF36613CEC58');
        $this->addSql('ALTER TABLE modulo DROP FOREIGN KEY FK_ECF1CF369FB704AB');
        $this->addSql('ALTER TABLE modulo_rol DROP FOREIGN KEY FK_A8962E624BAB96C');
        $this->addSql('ALTER TABLE modulo_rol DROP FOREIGN KEY FK_A8962E62C07F55F5');
        $this->addSql('ALTER TABLE modulo_rol DROP FOREIGN KEY FK_A8962E626BF700BD');
        $this->addSql('ALTER TABLE modulo_rol DROP FOREIGN KEY FK_A8962E629FB704AB');
        $this->addSql('CREATE INDEX FK_A8962E626BF700BD ON modulo_rol (status_id)');
        $this->addSql('ALTER TABLE nivel DROP FOREIGN KEY FK_AAFC20CB6BF700BD');
        $this->addSql('ALTER TABLE nivel DROP FOREIGN KEY FK_AAFC20CB9FB704AB');
        $this->addSql('ALTER TABLE opciones CHANGE puntos puntos INT DEFAULT NULL');
        $this->addSql('ALTER TABLE opciones_cargo DROP FOREIGN KEY FK_348153355BDBF2F');
        $this->addSql('ALTER TABLE opciones_cargo DROP FOREIGN KEY FK_34815335D1E12F15');
        $this->addSql('ALTER TABLE opciones_cargo DROP FOREIGN KEY FK_348153359FB704AB');
        $this->addSql('ALTER TABLE pais DROP FOREIGN KEY FK_7E5D2EFF6BF700BD');
        $this->addSql('ALTER TABLE pais DROP FOREIGN KEY FK_7E5D2EFF9FB704AB');
        $this->addSql('ALTER TABLE parametros DROP FOREIGN KEY FK_E09691179FB704AB');
        $this->addSql('ALTER TABLE pregunta DROP FOREIGN KEY FK_AEE0E1F76699F643');
        $this->addSql('ALTER TABLE pregunta DROP FOREIGN KEY FK_AEE0E1F710560508');
        $this->addSql('ALTER TABLE pregunta DROP FOREIGN KEY FK_AEE0E1F7396DC676');
        $this->addSql('ALTER TABLE pregunta DROP FOREIGN KEY FK_AEE0E1F77A5A413A');
        $this->addSql('ALTER TABLE pregunta DROP FOREIGN KEY FK_AEE0E1F79FB704AB');
        $this->addSql('ALTER TABLE pregunta_evaluacion DROP FOREIGN KEY FK_408F5ADE6699F643');
        $this->addSql('ALTER TABLE pregunta_evaluacion DROP FOREIGN KEY FK_408F5ADE10560508');
        $this->addSql('ALTER TABLE pregunta_evaluacion DROP FOREIGN KEY FK_408F5ADE593D2563');
        $this->addSql('ALTER TABLE pregunta_evaluacion DROP FOREIGN KEY FK_408F5ADE7A5A413A');
        $this->addSql('ALTER TABLE pregunta_evaluacion DROP FOREIGN KEY FK_408F5ADE9FB704AB');
        $this->addSql('ALTER TABLE proyecto DROP FOREIGN KEY FK_6FD202B99FB704AB');
        $this->addSql('ALTER TABLE proyecto DROP FOREIGN KEY FK_6FD202B95C473223');
        $this->addSql('ALTER TABLE proyecto DROP FOREIGN KEY FK_6FD202B9973E620A');
        $this->addSql('ALTER TABLE proyecto_adjunto DROP FOREIGN KEY FK_1646AC50EE371C4D');
        $this->addSql('ALTER TABLE proyecto_adjunto DROP FOREIGN KEY FK_1646AC5079F37AE5');
        $this->addSql('ALTER TABLE proyecto_adjunto DROP FOREIGN KEY FK_1646AC509FB704AB');
        $this->addSql('ALTER TABLE proyecto_rol DROP FOREIGN KEY FK_4EC328E7F625D1BA');
        $this->addSql('ALTER TABLE proyecto_rol DROP FOREIGN KEY FK_4EC328E74BAB96C');
        $this->addSql('ALTER TABLE recurso DROP FOREIGN KEY FK_B2BB37647DAF9E19');
        $this->addSql('ALTER TABLE recurso DROP FOREIGN KEY FK_B2BB376467B3B43D');
        $this->addSql('ALTER TABLE recurso DROP FOREIGN KEY FK_B2BB37649FB704AB');
        $this->addSql('ALTER TABLE recursos_proyecto DROP FOREIGN KEY FK_F7C598F330E4A115');
        $this->addSql('ALTER TABLE recursos_proyecto DROP FOREIGN KEY FK_F7C598F328827174');
        $this->addSql('ALTER TABLE recursos_proyecto DROP FOREIGN KEY FK_F7C598F39FB704AB');
        $this->addSql('ALTER TABLE redes DROP FOREIGN KEY FK_D7909F1B8700013');
        $this->addSql('ALTER TABLE redes DROP FOREIGN KEY FK_D7909F1B380CE5D8');
        $this->addSql('ALTER TABLE redes DROP FOREIGN KEY FK_D7909F1B9FB704AB');
        $this->addSql('ALTER TABLE respuesta DROP FOREIGN KEY FK_6C6EC5EE79F37AE5');
        $this->addSql('ALTER TABLE respuesta DROP FOREIGN KEY FK_6C6EC5EE29B74DE9');
        $this->addSql('ALTER TABLE respuesta DROP FOREIGN KEY FK_6C6EC5EE85880308');
        $this->addSql('ALTER TABLE respuesta DROP FOREIGN KEY FK_6C6EC5EE9FB704AB');
        $this->addSql('ALTER TABLE respuesta_evaluacion DROP FOREIGN KEY FK_459698AD79F37AE5');
        $this->addSql('ALTER TABLE respuesta_evaluacion DROP FOREIGN KEY FK_459698AD29B74DE9');
        $this->addSql('ALTER TABLE respuesta_evaluacion DROP FOREIGN KEY FK_459698AD85880308');
        $this->addSql('ALTER TABLE respuesta_evaluacion DROP FOREIGN KEY FK_459698AD9FB704AB');
        $this->addSql('ALTER TABLE rol DROP FOREIGN KEY FK_E553F37EBC2BC9A');
        $this->addSql('ALTER TABLE rol DROP FOREIGN KEY FK_E553F379FB704AB');
        $this->addSql('ALTER TABLE seccion DROP FOREIGN KEY FK_E0BD15C940B7B70');
        $this->addSql('ALTER TABLE seccion DROP FOREIGN KEY FK_E0BD15C96BF700BD');
        $this->addSql('ALTER TABLE seccion DROP FOREIGN KEY FK_E0BD15C99FB704AB');
        $this->addSql('ALTER TABLE seccion_evaluacion DROP FOREIGN KEY FK_9C3E60D9E715F406');
        $this->addSql('ALTER TABLE seccion_evaluacion DROP FOREIGN KEY FK_9C3E60D96BF700BD');
        $this->addSql('ALTER TABLE seccion_evaluacion DROP FOREIGN KEY FK_9C3E60D99FB704AB');
        $this->addSql('ALTER TABLE spring DROP FOREIGN KEY FK_6B3E146930E4A115');
        $this->addSql('ALTER TABLE spring DROP FOREIGN KEY FK_6B3E14699FB704AB');
        $this->addSql('ALTER TABLE spring ADD total_remaning_max INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sprint_item DROP FOREIGN KEY FK_24D98A324EBD432D');
        $this->addSql('ALTER TABLE sprint_item DROP FOREIGN KEY FK_24D98A32CCF2FB2E');
        $this->addSql('ALTER TABLE sprint_item DROP FOREIGN KEY FK_24D98A329FB704AB');
        $this->addSql('ALTER TABLE status DROP FOREIGN KEY FK_7B00651C9FB704AB');
        $this->addSql('ALTER TABLE statuscalendarioproyecto DROP FOREIGN KEY FK_241B1CFC9FB704AB');
        $this->addSql('ALTER TABLE statusisuues DROP FOREIGN KEY FK_82749D339FB704AB');
        $this->addSql('ALTER TABLE statuslaboral DROP FOREIGN KEY FK_B98B620D9FB704AB');
        $this->addSql('ALTER TABLE tamano_archivo_permitido DROP FOREIGN KEY FK_41C2B8FFBF8E41B');
        $this->addSql('ALTER TABLE tamano_archivo_permitido DROP FOREIGN KEY FK_41C2B8FC7E67E71');
        $this->addSql('ALTER TABLE tamano_archivo_permitido DROP FOREIGN KEY FK_41C2B8F9FB704AB');
        $this->addSql('ALTER TABLE telefono DROP FOREIGN KEY FK_C1E70A7F79F37AE5');
        $this->addSql('ALTER TABLE telefono DROP FOREIGN KEY FK_C1E70A7FEBC2BC9A');
        $this->addSql('ALTER TABLE telefono DROP FOREIGN KEY FK_C1E70A7F9FB704AB');
        $this->addSql('ALTER TABLE tipo_archivo DROP FOREIGN KEY FK_26D095229FB704AB');
        $this->addSql('ALTER TABLE tipo_categoria DROP FOREIGN KEY FK_AC7EAD636BF700BD');
        $this->addSql('ALTER TABLE tipo_categoria DROP FOREIGN KEY FK_AC7EAD639FB704AB');
        $this->addSql('ALTER TABLE tipo_categoria_evaluacion DROP FOREIGN KEY FK_EDB5A1F76BF700BD');
        $this->addSql('ALTER TABLE tipo_categoria_evaluacion DROP FOREIGN KEY FK_EDB5A1F79FB704AB');
        $this->addSql('ALTER TABLE tipo_cuenta_email DROP FOREIGN KEY FK_62E3A4549FB704AB');
        $this->addSql('ALTER TABLE tipo_estado DROP FOREIGN KEY FK_B3E417FB9FB704AB');
        $this->addSql('ALTER TABLE tipo_input DROP FOREIGN KEY FK_DE94A81F59BAB351');
        $this->addSql('ALTER TABLE tipo_input DROP FOREIGN KEY FK_DE94A81F9FB704AB');
        $this->addSql('ALTER TABLE tipo_item DROP FOREIGN KEY FK_1534F25B9FB704AB');
        $this->addSql('ALTER TABLE tipo_item CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE tipo_limited_bloqueo DROP FOREIGN KEY FK_101220889FB704AB');
        $this->addSql('ALTER TABLE tipo_operaciones DROP FOREIGN KEY FK_544EBBF69FB704AB');
        $this->addSql('ALTER TABLE tipo_orientacion DROP FOREIGN KEY FK_CE6A84889FB704AB');
        $this->addSql('ALTER TABLE tipo_status_archivo DROP FOREIGN KEY FK_B12A0CA79FB704AB');
        $this->addSql('ALTER TABLE tipo_unidad DROP FOREIGN KEY FK_665F26376BF700BD');
        $this->addSql('ALTER TABLE tipo_unidad DROP FOREIGN KEY FK_665F26379FB704AB');
        $this->addSql('ALTER TABLE tipo_unidad_evaluacion DROP FOREIGN KEY FK_45DB30B86BF700BD');
        $this->addSql('ALTER TABLE tipo_unidad_evaluacion DROP FOREIGN KEY FK_45DB30B89FB704AB');
        $this->addSql('ALTER TABLE tiporedes DROP FOREIGN KEY FK_809A38456BF700BD');
        $this->addSql('ALTER TABLE tiporedes DROP FOREIGN KEY FK_809A38459FB704AB');
        $this->addSql('ALTER TABLE token DROP FOREIGN KEY FK_5F37A13B79F37AE5');
        $this->addSql('ALTER TABLE token DROP FOREIGN KEY FK_5F37A13B9FB704AB');
        $this->addSql('ALTER TABLE type_event DROP FOREIGN KEY FK_35A28D509FB704AB');
        $this->addSql('CREATE INDEX FK_8D93D649D682C705 ON user (id_coordinacion_id)');
        $this->addSql('CREATE INDEX FK_8D93D649CE9EB679 ON user (id_gerencia_id)');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueado DROP FOREIGN KEY FK_EB980159786A81FB');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueado DROP FOREIGN KEY FK_EB9801598B42E401');
        $this->addSql('ALTER TABLE usuario_archivo_bloqueado DROP FOREIGN KEY FK_EB9801599FB704AB');
        $this->addSql('ALTER TABLE usuario_archivos DROP FOREIGN KEY FK_F04CF62A16915EA4');
        $this->addSql('ALTER TABLE usuario_archivos DROP FOREIGN KEY FK_F04CF62A730F69E5');
        $this->addSql('ALTER TABLE usuario_archivos DROP FOREIGN KEY FK_F04CF62A9FB704AB');
    }
}
